# individual linter configs go here
linters-settings:

# default linters are enabled `golangci-lint help linters`
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
